### ISSUE TITLE
编的时候报错了

### ISSUE THREAD

**Issue by wwy19841007** [shining1984/screader#3]
[ 50%] Building C object CMakeFiles/scread.dir/scread.c.o
/Users/magicyang/Desktop/codes/study/screader/scread.c:4:10: fatal error: 'clang-c/Index.h' file not found
#include <clang-c/Index.h>
         ^~~~~~~~~~~~~~~~~

**Comment by AirChen** [comment]
这里应该是引入libclang的头文件吧

**Comment by shining1984** [comment]
感谢关注，该问题已经修复。

以前环境不同，这次直接修复到clang-10.0.0。可以再试下。 @wwy19841007
